server:
  host: "localhost"
  port: 5000

mysql:
  name: "mydatabase"
  user: "user"
  password: "password"
  database: "autogen"
  host: "127.0.0.1"
  port: 3306

mariadb:
  name: "mydatabase"
  user: "root"
  password: "root"
  database: "mariadb_database_llm"
  host: "127.0.0.1"
  port: 3306

openai:
  api_key: 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
  model: gpt-4-1106-preview

azure:
  personal_access_token: p4snnqqatzyj6sbfquxazsyiegznujcdcyrhbtcrk5cxug2lriqq
  organization_url: https://dev.azure.com/fineto